language: python

python:
- 3.5
- 3.6
- 3.7

# required for python >= 3.7
dist: xenial

install:
- pip install pipenv
- pipenv sync --dev
- pipenv graph

script:
- pipenv run pytest --cov=freesurfer_surface --cov-report=term-missing --cov-fail-under=100
- pipenv run pylint --load-plugins=pylint_import_requirements freesurfer_surface
- pipenv run pylint tests/*

after_success:
- pip install coveralls
- coveralls
